### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Pluto-Really** [MaDHouSe79/qb-communityservice#1]
I havent touched it i just dragged and dropped and uploaded sql

![Capture](https://user-images.githubusercontent.com/92813476/160252260-548a30f9-247d-46ee-affa-c6544f07f6d9.PNG)

This is also how im trying to use it 
![Capture](https://user-images.githubusercontent.com/92813476/160252562-014f9529-08e7-4848-87db-ef6d4b512790.PNG)

**Comment by MaDHouSe79** [comment]
Hi, there is no error, you are using it wrong, you try to use a citizenid, but in fact it use the player netID then the identifier from QBcore. so if you type, `/comserv [id]` the person wil send, so you have to use the same id as you are using when you type it.

**Comment by Pluto-Really** [comment]
I am using netID not the citizenid  the "text = "Citizen ID" is just a label "
![Capture](https://user-images.githubusercontent.com/92813476/160254216-6fe66e31-e6aa-4038-95e0-fb9757de68e7.PNG)

**Comment by MaDHouSe79** [comment]
i just update the code, can you try if it works now?

**Comment by Pluto-Really** [comment]
Server Error
![Capture](https://user-images.githubusercontent.com/92813476/160275690-5af6e807-3ccb-4623-8248-29348d2f7fff.PNG)


Then Client Error
![Capture](https://user-images.githubusercontent.com/92813476/160275719-be8d0ab1-89c9-4516-a033-d3e48e2f1d72.PNG)

**Comment by MaDHouSe79** [comment]
if you can, send my your script so i can see what you are doing and fix it for you. just join my discord if you want :)

**Comment by MaDHouSe79** [comment]
i just update the code, and i tested it with this menu, i implemented this for you, you can download a new version to able to use this menu ;)

**Comment by Pluto-Really** [comment]
awesome thank you, i am in your discord :)
